# World of Numpy


NumPy is a wonderful Python package produced by Travis Oliphant, which
has been created fundamentally for scientific computing. It helps handle large
multidimensional arrays and matrices, along with a large library of high-level
mathematical functions to operate on these arrays.

## lists vs numpy
All Numpy array elements are of same type unlike lists.
Numpy data structures take up less space and better runtime behaviour.<br>
**Memory consumed by a list::**<br>
> contains a pointer to ablock of pointers, each of which in turn points to a full Python object<br>
It involves a header(64 bytes) and a refernce to the actual DS stores(8 byte addresses) and an int takes 24 bytes {different than int in C++ which is a data type while int in Python is a full fledged object} <br/>
    so totally = 64 + 8*len(list) + len(list)*24 <br>
    

**Memory consumed by a numpy array::**<br>
>As it doesnt multiple datatypes , numpy can store directly the data types rather than python objects that int can be stored in 8 bytes<br>
It involves a header followed by ints(8 bytes) 
    so totaly = 96 + len(arr)*8

A Python Integer is more than just an integer,it is similar to a C++ class. <br>
A int type object in python has <br>
struct _longobject {<br>
    &emsp;long ob_refcnt;<br>
    &emsp;PyTypeObject *ob_type;<br>
    &emsp;size_t ob_size;<br>
    &emsp;long ob_digit[1];<br>
};

In [55]:
#python data objects
import sys
print(sys.getsizeof(int()))
print(sys.getsizeof(str()))

24
49


In [2]:
import numpy as np

In [67]:
n_array = np.array([[0,1,2,3],[4,5,6,7]])
print(n_array)
#lot of attrivrutes which gives information about the anumpy arrays
print("ndim:", n_array.ndim) # number of dimensions
print("size:",n_array.size) #total number of elements
print("shape:", n_array.shape) 
print("dtype:",n_array.dtype)
print("itemsize:",n_array.itemsize,"bytes")
print("nbytes:",n_array.nbytes,"bytes") #size*itemsize

[[0 1 2 3]
 [4 5 6 7]]
ndim: 2
size: 8
shape: (2, 4)
dtype: int32
itemsize: 4 bytes
nbytes: 32 bytes


In [95]:
#arithmetic 
a = np.array([[1,2],[3,4]])
b = np.array([[0,1],[2,3]])
print(a-b);
print(a**2)
print(np.cos(a))

#conditional operators
#mind the use of &(bitwise) here instead of (and) which tries to do the falsehood of whole arrat which is not well defined
print((a<=2) & (a>1))


print(a*b) #element wise multiplication

#matrix multiplication
print(a.dot(b))
print(a@b)

[[1 1]
 [1 1]]
[[ 1  4]
 [ 9 16]]
[[ 0.54030231 -0.41614684]
 [-0.9899925  -0.65364362]]
[[False  True]
 [False False]]
[[ 0  2]
 [ 6 12]]
[[ 4  7]
 [ 8 15]]
[[ 4  7]
 [ 8 15]]


In [90]:
#subarrays(copies and views)

print(n_array)
print(n_array[:,2:])
print(n_array[:,2:-1])

print(n_array[::2,::-1]) ## linspace of 2 in rows and reverse in columns

#subarrays create views i.e; changes in the sub array are reflected in the main array
s_array = n_array[0,:]
s_array[0] = -1 #change first element in subaarray
print(n_array)
n_array[0,0]=0 # reset n_array
s_array_copy = n_array[0,:].copy() #creates a copy rather than a view
s_array_copy[0] = -1
print(n_array)

[[0 1 2 3]
 [4 5 6 7]]
[[2 3]
 [6 7]]
[[2]
 [6]]
[[3 2 1 0]]
[[-1  1  2  3]
 [ 4  5  6  7]]
[[0 1 2 3]
 [4 5 6 7]]


In [89]:
#array reshaping 
n_flat = n_array.ravel() #flatten
print(n_flat)
n_flat.shape = (4,2)
print(n_flat)
print(n_flat.transpose())
#easy reshape
n_array = np.arange(0,8).reshape((2,4))
print(n_array)

[0 1 2 3 4 5 6 7]
[[0 1]
 [2 3]
 [4 5]
 [6 7]]
[[0 2 4 6]
 [1 3 5 7]]
[[0 1 2 3]
 [4 5 6 7]]


In [94]:
#broadcasting (always add index 1 at left hand side)
a = np.arange(3)
b = np.arange(3)[:,np.newaxis]
print(a+b) #broadcasting of array b on a

[[0 1 2]
 [1 2 3]
 [2 3 4]]


array([4, 5, 6, 7])

In [97]:
#fancy indexing
X = np.arange(12).reshape((3,4))
print(X)
row = np.array([0,1,1])
col = np.array([2,1,3])
print(X[row,col])

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[2 5 7]


In [100]:
#numpy structured arrays (Use Pandas instead)
data = np.zeros(4,dtype={'names':('name','age','wt'),'formats':('U10','i4','f8')})
print(data.dtype)

[('name', '<U10'), ('age', '<i4'), ('wt', '<f8')]


In [103]:
#where with conditional arguments
result = np.where([True,False,True],[1,2,4],[5,6,7])
result

array([1, 6, 4])